name: Deploy GCF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn
      - run: yarn build
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true
      - run: |
          gcloud functions deploy registry-packer \
           --trigger-http \
           --runtime nodejs14 \
           --allow-unauthenticated \
           --region europe-west1 \
           --entry-point app \
           --set-env-vars NODE_ENV=production