name: Deploy GCF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn
      - run: yarn build
      - uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: registry-packer
          runtime: nodejs16
          entry_point: app
          region: europe-west1
          env_vars: NODE_ENV=production
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCLOUD_AUTH }}
